# Generated by Django 4.1 on 2022-08-30 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name="Ім'я автора")),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='book_author/', verbose_name='Мініатюра')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL автора')),
            ],
            options={
                'verbose_name': 'Письменник',
                'verbose_name_plural': 'Письменники',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL жанру')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Видавництво',
                'verbose_name_plural': 'Видавництва',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Назва')),
                ('year', models.PositiveSmallIntegerField(default=2022, verbose_name='Рік видання')),
                ('num_page', models.PositiveSmallIntegerField(default=200, verbose_name='Кількість сторінок')),
                ('format', models.CharField(max_length=50, verbose_name='Формат')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN')),
                ('language', models.CharField(max_length=30, verbose_name='Мова')),
                ('image', models.ImageField(upload_to='book_image/')),
                ('price', models.PositiveSmallIntegerField(default=252, verbose_name='Ціна')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL book')),
                ('availability', models.BooleanField(default=True, verbose_name='Наявність')),
                ('annotation', models.TextField(verbose_name='Анотація')),
                ('description', models.TextField(verbose_name='Опис')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='ebook.author', verbose_name='Автори')),
                ('genres', models.ManyToManyField(related_name='book_genre', to='ebook.genre', verbose_name='Жанри')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebook.publication', verbose_name='Видавництво')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('name',),
            },
        ),
    ]
